### ISSUE TITLE
newly created bot fails to start with an error loading nlc.confidence.high script

### ISSUE THREAD

**Issue by ramaboggarapu** [ibm-cloud-solutions/hubot-ibmcloud-cognitive-lib#94]
2016-09-14T14:05:35.57-0400 [App/0]      OUT [Wed Sep 14 2016 18:05:35 GMT+0000 (UTC)] ERROR Unable to load /home/vcap/app/node_modules/hubot-ibmcloud-nlc/src/scripts/nlc.confidence.high: TypeError: Cannot read property 'listen' of undefined
2016-09-14T14:05:35.57-0400 [App/0]      OUT   at new Conversation (/home/vcap/app/node_modules/hubot-conversation/lib/index.js:18:8)
2016-09-14T14:05:35.57-0400 [App/0]      OUT   at new EntityManager (/home/vcap/app/node_modules/hubot-ibmcloud-cognitive-entities/src/lib/entityManager.js:157:21)
2016-09-14T14:05:35.57-0400 [App/0]      OUT   at module.exports.robot.on.nlcDb.open.then.nlcconfig.getClassEmitTarget.then.entityManager.getEntities.then.catch.catch (/home/vcap/app/node_modules/hubot-ibmcloud-nlc/src/scripts/nlc.confidence.high.js:53:22)
2016-09-14T14:05:35.57-0400 [App/0]      OUT   at Robot.loadFile (/home/vcap/app/node_modules/hubot/src/robot.coffee:358:11)
2016-09-14T14:05:35.57-0400 [App/0]      OUT   at Array.forEach (native)
2016-09-14T14:05:35.57-0400 [App/0]      OUT   at /home/vcap/app/node_modules/hubot-ibmcloud-nlc/index.js:19:12
2016-09-14T14:05:35.57-0400 [App/0]      OUT   at FSReqWrap.oncomplete (fs.js:82:15)
2016-09-14T14:05:35.57-0400 [App/0]      OUT , Adapter: slack, Robot: cloudbot, Room: unknown, User: {}

**Comment by jlpadilla** [comment]
Fixed via https://github.com/ibm-cloud-solutions/hubot-ibmcloud-nlc/issues/96
